language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sardinhasantos/docker-react -f Dockerfile.dev .

script:
  - docker run sardinhasantos/docker-react npm run test -- --coverage